services:
  # ------ Database Services ------
  postgres-auth:
    image: postgres:13
    container_name: postgres-auth
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    ports:
      - "5431:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - business_platform_net

  postgres-crm:
    image: postgres:13
    container_name: postgres-crm
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: crm_db
    ports:
      - "5432:5432"
    volumes:
      - crm_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - business_platform_net

  postgres-sales:
    image: postgres:13
    container_name: postgres-sales
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sales_db
    ports:
      - "5433:5432"
    volumes:
      - sales_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sales_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - business_platform_net

  # ------ Backend Services ------
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: auth-service
    # The command now simply starts the application, as the build is part of the image.
    command: node dist/main
    ports:
      - "3001:3000"
    environment:
      - DATABASE_HOST=postgres-auth
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=auth_db
      - JWT_SECRET=aVeryStrongAndSecretKey123!@#ChangeMe
      - PORT=3000
    depends_on:
      postgres-auth:
        condition: service_healthy
    networks:
      - business_platform_net

  crm-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: crm-service
    # The command now simply starts the application.
    command: node dist/main
    ports:
      - "3002:3000"
    environment:
      - DATABASE_HOST=postgres-crm
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=crm_db
      - JWT_SECRET=aVeryStrongAndSecretKey123!@#ChangeMe
      - PORT=3000
    depends_on:
      postgres-crm:
        condition: service_healthy
    networks:
      - business_platform_net

  sales-service:
    build:
      context: .
      dockerfile: Dockerfile.backend
      args:
        SERVICE_NAME: sales-service
    # The command now simply starts the application.
    command: node dist/main
    ports:
      - "3003:3000"
    environment:
      - DATABASE_HOST=postgres-sales
      - DATABASE_PORT=5432
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=sales_db
      - JWT_SECRET=aVeryStrongAndSecretKey123!@#ChangeMe
      - PORT=3000
    depends_on:
      postgres-sales:
        condition: service_healthy
    networks:
      - business_platform_net

  # ------ Frontend Service ------
  web-client:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm run dev --workspace=web-client
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - auth-service
      - crm-service
      - sales-service
    networks:
      - business_platform_net

# ------ Volume Definitions ------
volumes:
  auth_db_data:
  crm_db_data:
  sales_db_data:

# ------ Network Definition ------
networks:
  business_platform_net:
    driver: bridge
